---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-06

ansible_user: root
ansible_port: 22

github_user: "freifunk-voreifel"

static_dhcp_repo: "https://github.com/{{ github_user }}/static-dhcp.git"

root_password_file: "root_pwd.yaml"

# Community GRE-tunnel prefix!
# Make sure, that no other interfaces has the same prefix. This would spoil ferm configuration.
#

gre_tunnel_prefix: "gre_"

# Yanic Communit Name
yanic_domain: "su-vor"

# Tunneldigger variables

# communitymac: "a2:8c:ae:7f:f7"

# communityname: "voreifel"

hoods:
  meckenheim:
    namespace: "meckenheim"
    number: 8
    address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_default_ipv4.alias }}"
    port: 20008
    max_tunnels: 512
    port_base: 8000
    tunnel_id_base: 8000
    dhcp:
      range: 10.152.65.1 10.152.78.254
      range6: "{{ ffrl.IPv6.prefix48 }}:0800::/64"
      NTP:  "10.152.64.2"
      DNS: "10.152.64.1"
      DNS6: "{{ ffrl.IPv6.prefix48 }}::1 , {{ ffrl.IPv6.prefix48 }}::2"
    mesh:
      iface: bat8
      mtu: 1312
      MAC: a2:8c:ae:6f:08:0{{ supernode.number }}
      IPv6:
        addr: "{{ ffrl.IPv6.prefix48 }}:0800::1"
        net: "{{ ffrl.IPv6.prefix48 }}:0800::/64"   # Prefix für radvd
        xfer: "{{ ffrl.IPv6.prefix48 }}:0800::2"
      IPv4:
        addr: 10.152.64.1
        brcast: 10.152.79.255
        net: 10.152.64.0
        netmask: 255.255.240.0
        CIDR: 20
        xfer: 10.152.64.2

  rheinbach: 
    namespace: "rheinbach"
    number: 10
    address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_default_ipv4.alias }}"
    port: 20010
    max_tunnels: 512
    port_base: 20000
    tunnel_id_base: 20000
    dhcp:
      range: 10.152.81.1 10.152.94.254
      range6: "{{ ffrl.IPv6.prefix48 }}:1000::/64"
      NTP:  "10.152.80.2"
      DNS: "10.152.80.1"
      DNS6: "{{ ffrl.IPv6.prefix48 }}::1 , {{ ffrl.IPv6.prefix48 }}::2"
    mesh:
      iface: bat10
      mtu: 1312
      MAC: a2:8c:ae:6f:10:0{{ supernode.number }}
      IPv6:
        addr: "{{ ffrl.IPv6.prefix48 }}:1000::1"
        net: "{{ ffrl.IPv6.prefix48 }}:1000::/64"   # Prefix für radvd
        xfer: "{{ ffrl.IPv6.prefix48 }}:1000::2"
      IPv4:
        addr: 10.152.80.1
        brcast: 10.152.95.255
        net: 10.152.80.0
        netmask: 255.255.240.0
        CIDR: 20
        xfer: 10.152.80.2

  meckenheimold:
    namespace: "meckenheimold"
    number: 13
    address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_default_ipv4.alias }}"
    port: 20013
    max_tunnels: 512
    port_base: 13000
    tunnel_id_base: 13000
    dhcp:
      range: 10.152.105.1 10.152.110.254
      range6: "{{ ffrl.IPv6.prefix48 }}:1300::/64"
      NTP:  "10.152.105.2"
      DNS: "10.152.105.1"
      DNS6: "{{ ffrl.IPv6.prefix48 }}::1 , {{ ffrl.IPv6.prefix48 }}::2"
    mesh:
      iface: bat13
      mtu: 1312
      MAC: a2:8c:ae:6f:13:0{{ supernode.number }}
      IPv6:
        addr: "{{ ffrl.IPv6.prefix48 }}:1300::1"
        net: "{{ ffrl.IPv6.prefix48 }}:1300::/64"   # Prefix für radvd
        xfer: "{{ ffrl.IPv6.prefix48 }}:1300::2"
      IPv4:
        addr: 10.152.104.1
        brcast: 10.152.111.255
        net: 10.152.104.0
        netmask: 255.255.248.0
        CIDR: 21
        xfer: 10.152.104.1

  rheinbachold: 
    namespace: "rheinbachold"
    number: 14
    address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_default_ipv4.alias }}"
    port: 20014
    max_tunnels: 512
    port_base: 14000
    tunnel_id_base: 14000
    dhcp:
      range: 10.152.113.1 10.152.119.254
      range6: "{{ ffrl.IPv6.prefix48 }}:1400::/64"
      NTP:  "10.152.112.2"
      DNS: "10.152.112.1"
      DNS6: "{{ ffrl.IPv6.prefix48 }}::1 , {{ ffrl.IPv6.prefix48 }}::2"
    mesh:
      iface: bat14
      mtu: 1312
      MAC: a2:8c:ae:6f:14:0{{ supernode.number }}
      IPv6:
        addr: "{{ ffrl.IPv6.prefix48 }}:1400::1"
        net: "{{ ffrl.IPv6.prefix48 }}:1400::/64"   # Prefix für radvd
        xfer: "{{ ffrl.IPv6.prefix48 }}:1400::2"
      IPv4:
        addr: 10.152.112.1
        brcast: 10.152.119.255
        net: 10.152.112.0
        netmask: 255.255.248.0
        CIDR: 21
        xfer: 10.152.112.2

  testfunk: 
    namespace: "testfunk"
    number: 15
    address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_default_ipv4.alias }}"
    port: 20015
    max_tunnels: 512
    port_base: 15000
    tunnel_id_base: 15000
    dhcp:
      range: 10.152.121.1 10.152.126.254
      range6: "{{ ffrl.IPv6.prefix48 }}:1500::/64"
      NTP:  "10.152.120.2"
      DNS: "10.152.120.1"
      DNS6: "{{ ffrl.IPv6.prefix48 }}::1 , {{ ffrl.IPv6.prefix48 }}::2"
    mesh:
      iface: bat15
      mtu: 1312
      MAC: a2:8c:ae:6f:15:0{{ supernode.number }}
      IPv6:
        addr: "{{ ffrl.IPv6.prefix48 }}:1500::1"
        net: "{{ ffrl.IPv6.prefix48 }}:1500::/64"   # Prefix für radvd
        xfer: "{{ ffrl.IPv6.prefix48 }}:1500::2"
      IPv4:
        addr: 10.152.120.1
        brcast: 10.152.127.255
        net: 10.152.120.0
        netmask: 255.255.248.0
        CIDR: 21
        xfer: 10.152.120.2

...
