---
ansible_user: root
ansible_port: 22

static_dhcp_repo: https://github.com/Freifunk-Troisdorf/static-dhcp.git

root_password_file: root_pwd.yaml

slack_token_file: slack_token.yaml

communitymac: "a2:8c:ae:7f:f7"
communityname: voreifel
