---
# file: playbooks/roles/gateways/tasks/tsk_mesh-nodes.yaml
#
# Thomas Arend
# Date 2019-06-22
#
#

# Install and configure mesh-nodes as a service

- name: stop batman + bridges
  service:
    name: "batman@{{ hoods[item].mesh.iface }}.service"
    state: stopped
  ignore_errors: true
  loop: "{{ hoods|list }}"

- name: Create bridge directory if they do not exist
  file:
    path: "/etc/freifunk"
    state: directory
    mode: '0755'
  ignore_errors: true
  tags: 
    - bridge

# Copy network templates to /etc/systemd/network/

- name: Copy bridge templates to /etc/systemd/network/
  template: 
    src: "{{ item.1 }}.j2"
    dest: "/etc/systemd/network/90-bridge-{{ hoods[item.0].mesh.iface }}.{{ item.1 }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ hoods|product(devtemplate)|list }}"
  vars:
    devtemplate:
      - netdev
      - link
  tags: 
    - bridge

# Tempate to add mesh-nodes to batman
# systemd-networkd hasn't any features to execute a command
# pre or post is going up or down

- name: Copy batman-up templates to /etc/freifunk/
  template: 
    src: "batman.sh.j2"
    dest: "/etc/freifunk/batman.sh"
    owner: root
    group: root
    mode: 0755
  tags: 
    - bridge

- name: Copy batman config /etc/freifunk/
  template: 
    src: "bat.conf.j2"
    dest: "/etc/freifunk/{{ hoods[item].mesh.iface }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ hoods|list }}"
  tags: 
    - bridge

- name: Copy bridge.service templates to /etc/systemd/
  template: 
    src: "batman.service.j2"
    dest: "/etc/systemd/system/batman@.service"
    owner: root
    group: root
    mode: 0644
  tags: 
    - bridge

# Excute "systemctl daemon-reload" after configs have been changed

- name: Force systemd to re-execute itself
  systemd:
    daemon_reexec: yes

# Excute "systemctl daemon-reload" after configs have been changed

- name: Enable and restart network
  service:
    name: "{{ item }}.service"
    state: restarted
    enabled: yes
  ignore_errors: true
  tags: 
    - bridge
  loop:
    - systemd-resolved
    - systemd-networkd

- name: Enable and restart batman + bridges
  service:
    name: "batman@{{ hoods[item].mesh.iface }}.service"
    state: restarted
    enabled: yes
  ignore_errors: true
  loop: "{{ hoods|list }}"

# End 
...
