---
#
# Main ansible role task for common installation 
#
# file: playbooks/roles/common/tasks/main.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Prepare host for ansible

- include_tasks: tsk_prep4ansible.yaml

# Include ssh keys for admin team

- include_tasks: tsk_ssh_adminteam.yaml

# Change the root password

- include_tasks: tsk_change_root_pwd.yaml

# Install all required packages

- include_tasks: tsk_packages.yaml

# Set IP addresses in /etc/hosts

- include_tasks: tsk_etc_hosts.yaml

# Replace time server in ntp.conf

- include_tasks: tsk_etc_logrotate.yaml

# Update kernel / grub

- include_tasks: tsk_kernel.yaml

# Insert required modules in /etc/modules directory

- include_tasks: tsk_etc_modules.yaml

# Create /opt/freifunk directory

- include_tasks: tsk_opt_freifunk.yaml

# Reboot and adjust clock

- include_tasks: tsk_reboot.yaml

...
