
- name: Reboot the server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered, no SMP"
  async: 1
  poll: 0
  ignore_errors: true
  when: 
    grubnosmp is changed 
    or sethostsipv4 is changed 
    or sethostsipv6 is changed
    or sethostname is changed
  
- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
  when: 
    grubnosmp is changed or 
    sethostsipv4 is changed or 
    sethostsipv6 is changed or
    sethostname is changed
