---
# Freifunk Voreifel
# Thomas Arend
# Date: 2019-04-13

# Install additional packages for Freifunk

- name: Adding Freifuck GPG Key
  apt_key:
    id: B2522557E6AB9BF5
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - apt

- name: add default repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://ftp.de.debian.org/debian/ {{ ansible_distribution_release }} main"
    - "deb http://ftp.de.debian.org/debian/ {{ ansible_distribution_release }}-updates main"
    - "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main"
    - "deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main"
    - "deb https://freifuck.de/debian {{ ansible_distribution_release }} main"
  when: ansible_distribution == "Debian"
  tags:
    - apt

- name: Update and upgrade packages
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    cache_valid_time: 86400 # One day 
  tags:
    - apt

- name: Install common required packages
  apt:
    name: "{{ common_required_packages }}"
    state: present
    update_cache: no
  register: aptupdates
  tags:
    - apt

- name: Upgrade from stretch to buster
  replace:
    path: /etc/apt/sources.list
    regexp: 'stretch'
    replace: 'buster'
  notify: apt upgrade
  tags:
    - apt

- name: Test if go is installed
  stat: 
    path: /usr/local/go/bin/go
  register: go_installed
  tags:
    - apt
  
- name: Install go
  shell: cd /usr/local && wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz -O go-release-linux-amd64.tar.gz && tar xvf go-release-linux-amd64.tar.gz && rm go-release-linux-amd64.tar.gz
  when: go_installed.stat.exists == False
  tags:
    - apt
  
- name: Adjust path for go
  lineinfile:
    dest: /root/.bashrc
    line: "{{ item }}"
  loop:
    - export GOPATH=/opt/go
    - export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  tags:
    - apt

- name: Gathering facts
  setup:

#
# Packages installed
#
