---
# Make VM for ansible compatible 
#

# We remove the DVD / CD ass source

- name: Remove cdrom in sources.list
  raw: "sed -i '/deb cdrom/c\\#' /etc/apt/sources.list"
  
# Fully working Ansible needs python, 
# We install python with module 'raw' instead of 'apt' in case there is no python available.

- name: Make this server ansible compatible
  raw: "apt-get install aptitude python apt-transport-https dirmngr -y"
 
