---
# Make VM for ansible compatible 
#

# We remove the DVD / CD ass source

- name: Remove cdrom in sources.list
  become: true
  raw: "sed -i '/deb cdrom/c\\#' /etc/apt/sources.list"
  
# Fully working Ansible needs python, 
# We install python with module 'raw' instead of 'apt' in case there is no python available.

# If the snapshot is a older, you need to update the systembefore making it Ansible compatible

- name: Update the repositories
  become: true
  raw: "apt-get update -y"

- name: Upgrade system
  become: true
  raw: "apt-get upgrade -y"

# Now we prepare for Ansible

- name: Make this server ansible compatible
  become: true
  raw: "apt-get install aptitude python apt-transport-https dirmngr -y"
 
