---

- name: disable multi CPU Kernel (SMP) # Wg. Fehler batman auf multi proc sys
  lineinfile: 
    dest: /etc/default/grub 
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet maxcpus=0 nosmp"'
    state: present
  register: grubnosmp
  tags:
    - kernel

- name: reduce timeout to 1 second
  lineinfile: 
    dest: /etc/default/grub 
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=1'
    state: present
  register: grubtimeout
  tags:
    - kernel
    
- name: update grub
  shell: update-grub2
  when: grubnosmp.changed or grubtimeout.changed
  tags:
    - grub
...
