---
all:
    children:
        debian:
            hosts:
                voreifel[1:2]:
        supernodes:
            hosts:
                voreifel[1:2]:
        hoods:
            hosts:
                voreifel[1:2]:
...

