---
all:
    children:
        debian:
            hosts:
                voreifel[1:2].freifunk-rhein-sieg.net:
        supernodes:
            hosts:
                voreifel[1:2].freifunk-rhein-sieg.net:

...
