- name: Reboot the server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered, no SMP"
    async: 1
    poll: 0
    ignore_errors: true
- name: waiting for server to come back (1st)
  local_action:
    wait_for
    host={{ inventory_hostname }}
    port=22
    delay=20
    timeout=300
