
- name: apt upgrade
  apt:
    upgrade: 'full'
    update_cache: 'yes'
    cache_valid_time: 86400 # One day 
  tags:
    - apt

- name: reload sshd
  shell: systemctl reload ssh

- name: reload resolv config
  shell: resolvconf -u
