---
# Erstellt von: Thomas Arend
# Erstellt / überarbeitet:  2019-07-06


- name: "Create ferm directory /etc/ferm"
  file: 
    path: "/etc/ferm"
    state: directory
    owner: root
    group: adm
    mode: 2750
  tags:
    - ferm
    
- name: "Create firewall rules for bgp"
  template:
    src: "ferm.conf.bgp.j2"
    dest: "/etc/ferm/ferm.conf"
    owner: root
    group: adm
    mode: 0644
  tags:
    - ferm
    
- name: Remove firewall rules for local nets on Voreifel99
  when: ansible_hostname == 'voreifel99'
  become: yes
  lineinfile:
    path: /etc/ferm/ferm.conf
    regexp: '(10\.0\.0\.0\/8|172\.16\.0\.0\/12|192\.168\.0\.0\/16) DROP\;'
    state: absent
  tags:
    - ferm    
    
- name: Enable and restart firewall ferm (ferm.service)
  service:
    name: "ferm.service"
    enabled: yes
    state: restarted
  tags: 
    - ferm
...
