---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Install and configure tunneldigger

- name: Create tunneldigger directories if they do not exist
  file:
    path: "/{{ item }}/tunneldigger"
    state: directory
    mode: '0755'
  loop:
    - etc
    - srv
    
# Stop the running tunneldigger before installing a new one
# Be aware we are stopping only hoods, which we have in the Ansible

- name: Stop service tunneldigger
  service:
    name: "tunneldigger@{{ hoods[item].namespace }}.service"
    state: stopped
  ignore_errors: True
  loop: "{{ hoods | list }}"
  tags: 
    - tunneldigger
    
# Get tunneldigger from github

- name: Get Tunneldigger
  git: 
    repo: https://github.com/{{ github_user }}/tunneldigger.git
    dest: /srv/tunneldigger
  register: tunneldigger
  tags: 
    - tunneldigger

# Install tunneldigger

- name: Configure tunneldigger
  raw: "cd /srv/tunneldigger && virtualenv env_tunneldigger && source env_tunneldigger/bin/activate && cd broker && python setup.py install"
  tags: 
    - tunneldigger

- name: Copy l2tp broker config template
  template: 
    src: "l2tp_broker.cfg.j2"
    dest: "/etc/tunneldigger/hood-{{ hoods[item].namespace }}.cfg"
    owner: root
    group: root
    mode: 0444
  loop: "{{ hoods | list }}"
  tags: 
    - tunneldigger

- name: Copy tunneldigger scripts
  copy: 
    src: "{{ item }}"
    dest: "/etc/tunneldigger"
    owner: root
    group: root
    mode: 0500
  loop:
    - bataddif.sh
    - batdelif.sh
    - ferm_fix.sh
    - blocklist
  tags: 
    - tunneldigger
    
- name: Apply tunneldigger / FERM fix startup script
  lineinfile:
    path: /etc/tunneldigger/ferm_fix.sh
    line: "/bin/systemctl restart tunneldigger@{{ hoods[item].namespace }}.service"
  loop: "{{ hoods | list }}"
  tags: 
    - tunneldigger   

- name: Copy tunneldigger / FERM fix service
  copy: 
    src: "tunneldigger_ferm_fix.service"
    dest: "/etc/systemd/system/tunneldigger_ferm_fix.service"
    owner: root
    group: root
    mode: 0500
  tags: 
    - tunneldigger    

- name: Copy tunneldigger service template
  template: 
    src: "tunneldigger.service.j2"
    dest: "/etc/systemd/system/tunneldigger@.service"
    owner: root
    group: root
    mode: 0444
  loop: "{{ hoods | list }}"
  tags: 
    - tunneldigger  

- name: Tunneldigger reload
  command: systemctl daemon-reload
  tags: 
    - tunneldigger

- name: Enable and restart service tunneldigger
  service:
    name: "tunneldigger@{{ hoods[item].namespace }}.service"
    enabled: yes
    state: restarted
  loop: "{{ hoods | list }}"
  tags: 
    - tunneldigger
    
- name: Enable tunneldigger / FERM fix
  service:
    name: "tunneldigger_ferm_fix.service"
    enabled: yes
    state: started
  tags: 
    - tunneldigger    
...
