---
# supernode/tasks/main.yaml

# Configure LAN Interfaces in /etc/network/interfaces.conf

# Create directory for interfaces

- name: delete old directories and files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/network/interfaces.d
    - /etc/network/interfaces

- name: create /etc/systemd/network 
  file:
    path: /etc/systemd/network
    state: directory
    mode: 0755

# Configure default Interfaces

- name: create ethernet config
  template:
    src: lo.network.j2
    dest: /etc/systemd/network/00-lo.network
    owner: root
    group: root
    mode: 0644

# Configure default interface

- name: Supernode 1. LAN interface
  template:
    src: eth0.network.j2
    dest: /etc/systemd/network/00-ether.network
    owner: root
    group: root
    mode: 0644

# Configure default interface

- name: Supernode 2. LAN interface
  template:
    src: eth1.network.j2
    dest: /etc/systemd/network/01-ether.network
    owner: root
    group: root
    mode: 0644

# Configure VLAN for X-link BATMAN

- name: Supernode VLAN interface for BATMAN X-link netdev
  template:
    src: "meshx.netdev.j2"
    dest: "/etc/systemd/network/40-meshx-{{ hoods[item].number }}.netdev"
    owner: root
    group: root
    mode: 0644
  loop: "{{ hoods|list }}"

- name: Supernode VLAN interface for BATMAN X-link network
  template:
    src: "meshx.network.j2"
    dest: "/etc/systemd/network/40-meshx-{{ hoods[item].number }}.network"
    owner: root
    group: root
    mode: 0644
  loop: "{{ hoods|list }}"

# We disabel old networkservices to switch to systemd networkd and resolved

- name: Disable services
  service:
    name: "{{ netservice }}"
    enabled: no
  ignore_errors: yes
  loop:
    - network
    - NetworkManager
  loop_control:
    loop_var: netservice
    
- name: Enable services
  service:
    name: "{{ netservice }}"
    enabled: yes
  loop:
    - systemd-networkd
  loop_control:
    loop_var: netservice

# Now we can enable systemd-resolved

- name: Enable services
  service:
    name: "{{ netservice }}"
    enabled: yes
  loop:
    - systemd-resolved
  loop_control:
    loop_var: netservice

- name: get status of /etc/resolv.conf
  stat: 
    path: /etc/resolv.conf
  register: sym

# We must direct static /etc/resolv.conf to systemd-reolved

- name: remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: create sym link /etc/resolv.conf to systemd resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: yes
...
