---
# supernode/tasks/main.yaml

# Configure LAN Interfaces in /etc/network/interfaces.conf

# Create directory for interfaces

- name: delete old directories and files
  file:
    path: {{ item }}
    state: absent
  loop:
    - /etc/network/interfaces.d
    - /etc/network/interfaces

- name: create /etc/systemd/network 
  file:
    path: /etc/systemd/network
    state: directory
    mode: 0755

# Configure default Interfaces

- name: create ethernet config
  template:
    src: lo.network.j2
    dest: /etc/systemd/network/00-lo.network
    owner: root
    group: root
    mode: 0644

# Configure systemd/network

- name: Supernode LAN interface
  template:
    src: eth0.network.j2
    dest: /etc/systemd/network/00-ether.network
    owner: root
    group: root
    mode: 0644

# Configure default Interfaces

- name: Disable services
  service:
    name: "{{ item }}"
    enabled: no
  ignore_errors: yes
  loop:
    - network
    - NetworkManager

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - systemd-networkd
    - systemd-resolved

- name: Disable services
  service:
    name: systemd-resolved
    state: restarted
    enabled: yes

- name: remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: create link to systemd resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
...
