---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-07-08
#
#

#
# Install yanic
#

- name: Stop a running yanic service
  service:
    name: "yanic.service"
    state: stopped
  ignore_errors: True
  tags: 
    - yannic
    
- name: Create Yanic user
  user:
    name: yanic
    comment: "Yanic service user"
  tags:
    - yanic

- name: Create Yanic folder
  file: 
    path: /opt/freifunk/yanic
    state: directory
    mode: 0755
    owner: yanic
    group: yanic
  tags:
    - yanic

- name: Copy yanic config template
  template:
    src: yanic.conf.j2
    dest: /etc/yanic.conf
    owner: yanic
    group: yanic
    mode: 0444
  tags:
    - yanic

- name: Compile yanic with go
  shell: "go get -v -u github.com/{{ github_user }}/yanic"
  ignore_errors: True
  register: compile_yanic
  tags:
    - yanic
  
- name: Copy and enable yanic service
  shell: "cp /opt/go/src/github.com/{{ github_user }}/yanic/contrib/init/linux-systemd/yanic.service /lib/systemd/system/yanic.service"
  when: compile_yanic is succeeded
  tags:
    - yanic
    
- name: Reload daemons after service change
  command: systemctl daemon-reload
  when: compile_yanic is succeeded
  tags: 
    - tunneldigger

- name: Enable and restart service yannic
  service:
    name: "yanic.service"
    enabled: yes
    state: restarted
  when: compile_yanic is succeeded
  tags: 
    - yannic

...
