---
# Erstellt von: Thomas Arend
# Erstellt am:  2020-02-02

- name: "Testing supernode installation"
  include_tasks: "{{ task_item }}"
  loop:
    - ipv4.yaml
    - ipv6.yaml
    - domains.yaml
    - test_script.yaml
  loop_control:
    loop_var: task_item
    
...
    
