---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-06-23

- name: Delete servers and pool from ntp.conf
  lineinfile:
    dest: /etc/ntp.conf
    regexp: '(^pool|^server) .*'
    state: absent
  when: provider is defined

- name: Insert server into /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ item }} iburst"
  loop: "{{ ntp_server[provider] | list }}"
  when: provider is defined
  
- name: Restart ntp
  service:
    name: ntp.service
    state: restarted
  when: provider is defined
...
