#---
#
# Main ansible role task for dns installation 
#
# file: playbooks/roles/gateways/tasks/tsk_dnsserver.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

- name: Create /etc/bind/zones
  file: 
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 1755
  tags:
    - dns
    
- name: Copy FF Zones
  copy:
    src: "{{ item }}"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: 
    mode: 0644
  tags:
    - dns
  loop: 
    - named.conf.freifunk
    
- name: Activate ff zone
  lineinfile:
    dest: /etc/bind/named.conf.local
    line: 'include "/etc/bind/named.conf.freifunk";'
    state: present
  tags:
    - dns

- name: Copy option template
  template: 
    src: named.conf.options.j2 
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  tags:
    - dns

- name: Copy ff Zone config template
  template: 
    src: db.ff.j2 
    dest: /etc/bind/zones/db.ff 
    owner: root
    group: bind
    mode: 0444
  tags:
    - dns
    
- name: Add provider specific DNS Server
  lineinfile: dest=/etc/bind/named.conf.options
              line=' {{ item }};'
              insertafter='// Ansible DNS Servers //'
  loop: "{{ dns_server[provider] | list }}"
  when: provider is defined and dns_server[provider] is defined          
  tags: 
    - dns   

- name: Add default DNS Server
  lineinfile: dest=/etc/bind/named.conf.options
              line='{{ item }};'
              insertafter='// Ansible DNS Servers //'
  loop: "{{ dns_server[default] | list }}"
  when: dns_server[provider] is not defined          
  tags: 
    - dns     

- name: Restart DNS Server
  service:
    name: bind9
    enabled: yes
    state: restarted
  tags:
    - dns
