---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-08

# Configure netfilter in /etc/sysctl.conf

#
# netfilter
#

- name: Set netfilter rules in sysctl.conf
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  loop:
    - "net.ipv4.ip_forward = 1"           # GRE tunneling requires IP forwarding
    - "net.ipv6.conf.all.forwarding = 1"  # GRE tunneling requires IP forwarding
    - "net.ipv4.conf.bat0.rp_filter=0"    # Move from startup scrit to config
    - "net.ipv4.netfilter.ip_conntrack_generic_timeout = 240"
    - "net.ipv4.netfilter.ip_conntrack_tcp_timeout_established = 54000"
    - "net.netfilter.nf_conntrack_max = 65536"
    - "kernel.panic=1"
    
- name: Reload sysctl
  raw: "sysctl --system"
