---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-08

# Configure netfilter in /etc/sysctl.conf

#
# netfilter
#

- name: Set net.ipv4.ip_forward
  sysctl:
    name: "net.ipv4.ip_forward"
    value: "1"
    sysctl_set: yes
    state: present
    reload: no

# solves issue #9
    
- name: Set net.ipv4.tcp_l3mdev_accept
  sysctl:
    name: "net.ipv4.tcp_l3mdev_accept"
    value: "1"
    sysctl_set: yes
    state: present
    reload: no

- name: Set net.ipv6.conf.all.forwarding
  sysctl:
    name: "net.ipv6.conf.all.forwarding"
    value: "1"
    sysctl_set: yes
    state: present
    reload: no

# solves issue #10

- name: Set net.netfilter.nf_conntrack_generic_timeout
  sysctl:
    name: "net.netfilter.nf_conntrack_generic_timeout"
    value: "240"
    sysctl_set: yes
    state: present
    reload: no

# solves issue #10

- name: Set net.netfilter.nf_conntrack_tcp_timeout_established
  sysctl:
    name: "net.netfilter.nf_conntrack_tcp_timeout_established"
    value: "54000"
    sysctl_set: yes
    state: present
    reload: no

- name: Set net.netfilter.nf_conntrack_max
  sysctl:
    name: "net.netfilter.nf_conntrack_max"
    value: "65536"
    sysctl_set: yes
    state: present
    reload: no

- name: Set netfilter rules in sysctl.conf for bat devices
  sysctl:
    name: "net.ipv4.conf.{{ hoods[item].mesh.iface }}.rp_filter"
    value: "0"
    sysctl_set: no
    state: present
    reload: no
  loop: "{{ hoods|list }}"

- name: Set kernel.panic
  sysctl:
    name: "kernel.panic"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

