---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#
#
# respondd
#

- name: Stop and disable respondd service
  service:
    name: "respondd.service"
    enabled: no
    state: stopped
  ignore_errors: True

- name: Get respondd
  git: 
#    repo: "https://github.comg/{{ github_user }}/mesh-announce.git"
    repo: "https://github.com/Byggvir/mesh-announce.git"
    dest: "/opt/mesh-announce"
  register: get_respondd

- name: Create respondd config dir in /etc
  file:
    path: "/etc/respondd"
    state: directory
    mode: '0755'
  ignore_errors: true

- name: Copy respondd.service template to /etc/systemd/system
  template: 
    src: "respondd@.service.j2"
    dest: "/etc/systemd/system/respondd@.service"
    owner: root
    group: root
    mode: 0644

- name: Copy resspondd config to /etc/respondd/
  template: 
    src: "respondd.json.j2"
    dest: "/etc/respondd/{{ hoods[item].mesh.iface }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ hoods|list }}"

- name: Enable respondd service
  command: "systemctl daemon-reload"
  when: get_respondd is succeeded

- name: Enable and restart respondd
  service:
    name: "respondd@{{ hoods[item].mesh.iface }}.service"
    state: restarted
    enabled: yes
  ignore_errors: true
  loop: "{{ hoods|list }}"
  when: get_respondd is succeeded
...
