---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-20

# Ab hier muss noch dein Code hinein

sn_rootpasswd: $6$A3P5wEa0JF9vlU$VaGPmom4TIt9T.yVC7gSIynv8zGMR9HQeviR8UnA6KQmKDJ6JnyzxM4oGAFYszwAuVcity.nV0dmHIqVlPpMS/ 
...
