---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-11

# Ab hier muss noch dein Code hinein

- name: restart systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
    state: restarted

...
