---
# Stand: 2019-06-18
#
# Super node 99 for testing 

ansible_host: "192.168.2.70"
ansible_user: "thomas"

provider: 'hetzner'

ffrl:
    IPv4: 
      addr: 185.66.193.126
    IPv6: 
      addr: 2a03:2260:301a::1
      net: 2a03:2260:301a::/48
    iface: "gre_uplink"

supernode:
    number: 1
    hostname: "{{inventory_hostname_short}}"
    fqdn: "ff"
    asn: 65201

communitymac: 05:32:be:5b:12

ul_mesh_MAC: a2:8c:ae:6f:f7:10

## Lokaler exit
#sn_local_exit: 1

## Exit über FFRL
sn_exit: 1

## GRE Tunnel definition

#Endpunkte

    # bb-a.ak.ber 185.66.195.0
    # bb-b.ak.ber 185.66.195.1
    # bb-a.ix.dus 185.66.193.0
    # bb-b.ix.dus 185.66.193.1
    # bb-a.fra3.fra 185.66.194.0
    # bb-b.fra3.fra 185.66.194.1
    
gre:
  ber_a:
    description: "Rheinland Backbone Berlin A"
    remote: '192.168.2.71'
    local:  '{{ ansible_default_ipv4.address }}'
    netmask: '255.255.255.254'
    mtu: 1400
    ttl: 64
    dev: '{{ gre_tunnel_prefix }}ber_a' # Used for Bird, '-' not allowed
    address: '100.64.10.43'
    daddress: '100.64.10.42'
    network: '100.64.10.42/32'
    inet6: '2003:e2:af12:1a00:a00:27ff:fe06:3531'
    dinet6: '2003:e2:af12:1a00:a00:27ff:fe5e:7702'
    asn: 201701

...
