#---
#
# Main ansible role task for gateway installation 
#
# file: playbooks/roles/gateways/tasks/main.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Configure interfaces

- name: "Update modprobe"
  include_tasks: tsk_modprobe.yaml
  
- name: "Configure interfaces"
  include_tasks: tsk_interfaces.yaml

- name: "Configure bridge br-nodes for batman"
  include_tasks: tsk_br-nodes.yaml

- name: "Configure GRE tunnels to FFRL"
  include_tasks: tsk_gre-tunnel.yaml

- name: "Configure Routing"
  include_tasks: tsk_routing.yaml

# ferm configuration is moved to role
#- name: "Configure Firewall ferm"
#  include_tasks: tsk_ferm.yaml

# Bird configuration is moved to role
#- name: "Configure netfilter"
#  include_tasks: tsk_netfilter.yaml

# Bird configuration is moved to role
#- name: "Configure Bird" 
#  include_tasks: tsk_bird.yaml
  
# Tunneldigger configuration is moved to role
#- name: "Configure Tunneldigger"
#  include_tasks: tsk_tunneldigger.yaml

# DNS configuration is moved to role
#- name: "Configure DNS Server"
#  include_tasks: tsk_dnsserver.yaml

  
# DHCP configuration is moved to role
#- name: "Configure DHCP Server"
#  include_tasks: tsk_dhcp.yaml

# Yannic is moved to role
#- name: "Create and configure yanic"
#  include_tasks: tsk_yanic.yaml
#

# Respondd is moved to role
#- name: "Configure respondd"
#  include_tasks: tsk_respondd.yaml

# Obsolete Startup Scripte
#- name: "Configure startup"
#  include_tasks: tsk_startup.yaml
...
