#---
#
# Main ansible role task for gateway installation 
#
# file: playbooks/roles/gateways/tasks/main.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Configure interfaces

- name: "Configure interfaces"
  include_tasks: tsk_interfaces.yaml

- name: "Configure netfilter"
  include_tasks: tsk_netfilter.yaml

- name: "Configure GRE tunnels to FFRL"
  include_tasks: tsk_gre-tunnel.yaml

- name: "Configure Bird" 
  include_tasks: tsk_bird.yaml

- name: "Configure DNS Server"
  include_tasks: tsk_dnsserver.yaml

- name: "Configure Tunneldigger"
  include_tasks: tsk_tunneldigger.yaml

...
