#---
#
# Main ansible role task for gateway installation 
#
# file: playbooks/roles/gateways/tasks/main.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Configure interfaces

- include_tasks: tsk_interfaces.yaml

# Set netfilter

- include_tasks: tsk_netfilter.yaml

# Configure GRE tunnels to FFRL

- include_tasks: tsk_gre-tunnel.yaml

# Install Bird 

- include_tasks: tsk_bird.yaml

# Configure DNS Server

- include_tasks: tsk_dnsserver.yaml

# Configure Tunneldigegr

- include_tasks: tsk_tunneldigger.yaml


...
