---
# file: playbooks/roles/gateways/tasks/tsk_br-nodes.yaml
#
# Thomas Arend
# Date 2019-06-22
#
#

# Install and configure br-nodes as a service

- name: Create bridge directory if they do not exist
  file:
    path: "/etc/freifunk"
    state: directory
    mode: '0755'
  ignore_errors: true
  tags: 
    - bridge

# Copy network templates to /etc/systemd/network/

- name: Copy bridge templates to /etc/systemd/network/
  template: 
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - br-nodes.netdev
    - br-nodes.link
  tags: 
    - bridge

# Tempate to add br-nodes to batman
# systemd-networkd hasn't any features to execute a command
# pre or post is going up or down


- name: Copy bridge.service templates to /etc/systemd/
  template: 
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - bridge.service
  tags: 
    - bridge

# Excute "systemctl daemon-reload" after configs have been changed

- name: Force systemd to re-execute itself
  systemd:
    daemon_reexec: yes

# Excute "systemctl daemon-reload" after configs have been changed

- name: Enable and restart network services
  service:
    name: "{{ item }}.service"
    state: restarted
    enabled: yes
  ignore_errors: true
  tags: 
    - bridge
  loop:
    - systemd-resolved
    - systemd-networkd
    - bridge

# End 
...
