# supernode/tasks/tsk_gre-tunnel.yaml
#
# Thomas Arend
# Date 2019-04-13
#

# Configure GRE Tunnles in /etc/network/interfaces.d/{{ item }}.conf

- name: "Create directory"
  file:
    path: "/etc/bird"
    state: directory
    mode: 0755
  tags:
    - bird

- name: "bird configuration"
  template:
    src: bird.conf.j2
    dest: "/etc/bird/bird.conf"
    owner: bird
    group: bird
    mode: 0444
  tags:
    - bird

- name: "bird6 configuration"
  template:
    src: bird6.conf.j2
    dest: "/etc/bird/bird6.conf"
    owner: bird
    group: bird
    mode: 0444
  tags:
    - bird
