---
# supernode/tasks/main.yaml

# Configure LAN Interfaces in /etc/network/interfaces.conf

# Create temprary directory for testing Ansible

- file:
    path: /etc/network
    state: directory
    mode: 0755

# Create directory for interfaces

- file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

# Configure default Interfaces

- name: Supernode LAN
  template:
    src: iface-lan.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    
# Configure default Interfaces

- name: IFACE FFRL uplink 
  template:
    src: iface-uplink.j2
    dest: /etc/network/interfaces.d/ffrl_uplink
    owner: root
    group: root
    mode: 0644
...
