---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

# Install and configure tunneldigger
- name: Exit node startup script super- and exitnode
  template: 
    src: ./files/sn_startup.exit.sh.j2
    dest: /opt/freifunk/sn_startup.sh
    owner: root
    group: root
    mode: 0500
  when: sn_exit is defined
    
- name: Exit node startup script super- and exitnode # local fuer lokales testen
  template: 
    src: ./files/sn_startup.local.exit.sh.j2
    dest: /opt/freifunk/sn_startup.sh
    owner: root
    group: root
    mode: 0500
  when: sn_local_exit is defined
