---
#
# Ferm firewall configuration
#
# file: playbooks/roles/gateways/tasks/tsk_ferm.conf
#
# Thomas Arend
# Date 2019-06-20
#

- name: "Configure Firewall"
  include_role: 
    name: firewall
  tags:
    - ferm
...
