---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#
#
# respondd
#

- name: Get respondd
  git: 
    repo: https://github.com/{{ github_user }}/mesh-announce.git
    dest: /opt/mesh-announce
  tags: 
    - respondd

- name: Copy respondd service template
  shell: cp /opt/mesh-announce/respondd.service /etc/systemd/system
  tags: 
    - respondd

- name: Enable respondd service
  shell: systemctl daemon-reload && systemctl enable respondd
  tags: 
    - respondd
...
