---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

#
# Install yanic
#

- name: Create Yanic user
  user:
    name: yanic
    comment: "Yanic service user"

- name: Create Yanic folder
  file: 
    path: /opt/freifunk/yanic
    state: directory
    mode: 0755
    owner: yanic
    group: yanic

- name: Copy Yanic config template
  template:
    src: yanic.conf.j2
    dest: /etc/yanic.conf
    owner: yanic
    group: yanic
    mode: 0444

...
