---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-07-27

- name: Copy GRE tunnel templates to /etc/systemd/network/
  template: 
    src: "vrf.netdev.j2"
    dest: "/etc/systemd/network/30-vrf.netdev"
    owner: root
    group: root
    mode: 0644
...
