---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-04-17

- name: Make host ansible compatible
  hosts: all
  gather_facts: no
  become: true
  become_method: su
  tasks:
    - include_role:
        name: ansible-compatible
...
