---
# Playbook to change root password
#
#
- name: Change root password on FF super nodes
  hosts: all
  user: root
  gather_facts: False
  tasks:
    - include_tasks: ../tasks/tsk_change_root_pwd.yaml
...
