---
# Playbook to install all components via roles!
# Thomas Arend
# Stand 2019-04-17

#- name: Install common components
  #hosts: all
  #gather_facts: true
  #become: true
  #tasks:
    #- include_role:
        #name: common

- name: Install supernode components
  hosts: all
  gather_facts: true
  become: true
  vars: 
    snversion: master_v0.1.0
    modules_required:
      - batman-adv
      - nf_conntrack_netlink
      - nf_conntrack
      - nfnetlink
      - l2tp_netlink
      - l2tp_core
      - l2tp_eth
    tunneldigger_scripts:
      - start-broker.sh
      - batdelif.sh
    tunneldigger_service:
      - tunneldigger.service
    respondd_service:
      - respondd_service
    broker_cfg:
      - l2tp_broker.cfg
    logrotate_config:
      - logrotate.conf

  tasks:
    - include_role:
        name: supernode
...


