---
# Install FF Voreifel super node from playbooks
# pb_install-all.yaml
#
# Stand: 2019-02-10
- import_playbook: pb_addsshkeys.yaml
- import_playbook: pb_packages.yaml
- import_playbook: pb_slack.yaml
- import_playbook: pb_bird.yaml
- import_playbook: pb_tunneldigger.yaml

