---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-04-17

- name: Install common components
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - include_role:
        name: common

- name: Install supernode components
  hosts: supernodes
  gather_facts: yes
  become: yes
  tasks:
    - include_role:
        name: supernode

- name: "Test supernode"
  hosts: supernodes
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: testing
...
