---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-07-08

- name: Install common components
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name:  Basic installation for all servers
      include_role:
        name: common

    - name: Configure NTP (Server / Client)
        name: ntpserver

# Supernode (first steps)

- name: Install supernode components
  hosts: supernodes
  tasks:
    - name: First steps 
      include_role:
        name: supernode
        
    - name: Configure Netfilter
      include_role:
        name: netfilter
    
    # bird / bird6 

    - name: Configure bird  and bird6
      include_role:
        name: bird

    # Tunneldigger 

    - name: Install and configure tunneldigger
      include_role:
        name: tunneldigger
    
    - name: Configure DNS Server (bind9)
      include_role:
        name: dnsserver
        
    # DHCP
    
    # Da der DHCP Server auf der Tunnel Bridge oder dm BATMAN Interface lauscht,
    # kommt zum Schluss, denn ohne bat0 oder br-nodes startet er nicht. 

    - name: Install DHCP server isc-dhcp-server
      include_role:
        name: dhcpserver

    - naem: Configure radvd
      include_role:
        name: radvd

# Für die reine Gateway-Funktion nicht erforderliche Dienste

# Sonstiges

- name: Install yannic
  hosts: supernodes
  tasks:
    - name: Install and configure yanic
      include_role:
        name: yannic
    - name: Insatll and configure respondd
      include_role:
        name: respondd
   - tags:
     - sonstiges
#
# Installation / update completed
# Just log our update  
#

- name: Write installation / update date
  hosts: all
  become: true
  tasks:
    - name: Log update
      shell: 'echo -e "Last updated by Ansible: $(date +%F\ %X)" >> /etc/supernode.version'

#
# Restart the supernode
#

    - name: Reboot the server finally
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local

#
# Test the new supernode
#

- name: "Test supernode"
  hosts: supernodes,!voreifel99
  gather_facts: no
  become: true
  tasks:
    - include_role:
        name: testing
...
