---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-04-17

- name: Install common components
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - include_role:
        name: common

- name: Install supernode components
  hosts: supernodes
  gather_facts: yes
  become: yes
  tasks:
    - include_role:
        name: supernode

#
# Installation / update completed
# Just log our update  
#

- name: Write installation / update date
  hosts: all
  tasks:
    - name: Log update
      shell: 'echo -e "Last updated by Ansible: $(date +%F\ %X)" >> /etc/supernode.version'

#
# Restart the supernode
#

    - name: Reboot the server finally
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back
      local_action:
        wait_for
        host={{ inventory_hostname }}
        port=22
        delay=20
        timeout=300

#
# Test the new supernode
#

- name: "Test supernode"
  hosts: supernodes
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: testing
        

...
