---

- name: Install supernode components
  hosts: supernodes
  gather_facts: yes
  become: true
  tags:
    -supernode
  tasks:
    - name: Configure modprobe 
      include_role:
        name: "{{ required_role }}"
      loop:
        - batman
        - firewall
        - dhcpserver
        - tunneldigger
      loop_control:
        loop_var: required_role 
