---
# Install FF Voreifel super node from playbooks
#
# install slack
#
# pb_install-all.yaml
#
# Stand: 2019-02-12

- name: Install slack
  hosts: all
  user: root
  gather_facts: False
  vars: 
    - include_vars: "../{{ slack_token_file }}"
  tasks:
    - include_tasks: "../tasks/tsk_slack.yaml"
