---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-04-17

- name: "Test supernode"
  hosts: supernodes
  gather_facts: yes
  become: yes
  tasks:
    - raw: "echo '{{ item.1 }}.j2 + /etc/systemd/network/90-bridge-{{ hoods[item.0].mesh.iface }}.{{ item.1 }}' >>/tmp/itemlist"
      loop: "{{ hoods|product(devtemplate)| list }}"
      vars:
        devtemplate:
          - netdev
          - link
...
