---
# Playbook to install all components via roles!
# Thoasm Arend
# Stand 2019-04-17

- name: Test super node network
  hosts: supernodes
  gather_facts: yes
  become: true
  tags:
    -supernode
  tasks:
    - name: Test network 
      include_role:
        name: "{{ required_role }}"
      loop:
        - testing
      loop_control:
        loop_var: required_role 
...
