---
# supernode/tasks/tsk_gre-tunnel.yaml
#
# Thomas Arend
# Date 2019-04-13
#

- name: Copy GRE tunnel templates to /etc/systemd/network/
  template: 
    src: "gre.{{ item.1 }}.j2"
    dest: "/etc/systemd/network/20-gre-{{ item.0 }}.{{ item.1 }}"
    owner: root
    group: root
    mode: 0644
  when: gre[item.0].enabled is defined and gre[item.0].enabled == true
  notify: restart systemd-networkd
  loop: "{{ gre|product(devtemplate)|list }}"
  vars:
    devtemplate:
      - netdev
      - network

- name: delete disabled GRE tunnels
  file: 
    path: "/etc/systemd/network/20-gre-{{ item.0 }}.{{ item.1 }}"
    state: absent
  when: gre[item.0].enabled is defined and gre[item.0].enabled == false
  notify: restart systemd-networkd
  loop: "{{ gre|product(devtemplate)|list }}"
  vars:
    devtemplate:
      - netdev
      - network

- meta: flush_handlers
...
