# supernode/tasks/tsk_gre-tunnel.yaml
#
# Thomas Arend
# Date 2019-04-13
#

# Configure GRE Tunnles in /etc/network/interfaces.d/{{ item }}.conf

- name: FFRL GRE Tunnel configuration
  template:
    src: "iface-gre-tunnel.j2"
    dest: "/etc/network/interfaces.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  when: gre[item].enabled is defined and gre[item].enabled == true
  tags:
    - gre
  loop: "{{ gre | list }}"
  
